# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='beacon_parameters',
            field=models.CharField(blank=True, help_text='ex. tit=mail_magazine_title&oid=2', max_length=256),
        ),
    ]
