# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-07 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20170614_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_id',
            field=models.SlugField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
