apiVersion: v1
items:
- apiVersion: v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "7"
    creationTimestamp: 2016-06-02T11:45:06Z
    generation: 15
    labels:
      run: oceanus
    name: oceanus
    namespace: default
    resourceVersion: "28126"
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/oceanus
    uid: 735dae17-28b7-11e6-8e59-42010af00068
  spec:
    replicas: 2
    selector:
      matchLabels:
        run: oceanus
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: oceanus
      spec:
        containers:
        - image: us.gcr.io/oceanus-dev/oceanus-collect:v0.33
          imagePullPolicy: IfNotPresent
          name: oceanus
          ports:
          - containerPort: 80
            hostPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        hostNetwork: true
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
kind: List
metadata: {}
