# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-09 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_url_beacon_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='beacon_parameters',
            field=models.CharField(blank=True, help_text='ex. tit=mail_magazine_title&oid=2', max_length=512),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(max_length=512),
        ),
    ]
