FROM python:3.5-alpine
MAINTAINER yu_yamazaki@bizocean.co.jp

RUN pip3 install -q \
bigquery-python \
memory_profiler \
google-api-python-client

ENV PROJECT_ID your_project
ENV DATA_SET your_dataset
ENV BQ_TABLE_PREFIX oceanus_v3_
ENV JSON_KEY_FILE keys/your_google_key_file.json

RUN mkdir /oceanus/
COPY app /oceanus/app

WORKDIR /oceanus/app/

CMD ["python3.5","table-manager.py"]
