FROM python:3.5-alpine
MAINTAINER yu_yamazaki@bizocean.co.jp

RUN pip3 install --upgrade -q \
bigquery-python \
google-api-python-client \
redis

ENV PROJECT_ID oceanus-dev
ENV DATA_SET oceanus_prod
ENV JSON_KEY_FILE keys/your_google_key_file.json
ENV BQ_TABLE_PREFIX oceanus_v3_

ENV REDISMASTER_SERVICE_HOST localhost
ENV REDISMASTER_SERVICE_PORT 6379
ENV LOG_LEVEL WARNING

RUN mkdir /oceanus/
COPY app /oceanus/app
WORKDIR /oceanus/app/

CMD ["python3.5","redis2bq.py"]
