# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-30 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='sql',
            new_name='download_sql',
        ),
        migrations.AddField(
            model_name='query',
            name='preview_sql',
            field=models.TextField(blank=True),
        ),
    ]
