# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-31 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_auto_20170830_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='use_legacy_sql',
            field=models.BooleanField(default=True),
        ),
    ]
