# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-31 08:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_query_use_legacy_sql'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='download_sql',
            field=models.TextField(help_text='\u9069\u5ea6\u306bLIMIT 5000\u7a0b\u5ea6\u304b\u3051\u3066\u304f\u3060\u3055\u3044\u3002{START_DATE} {END_DATE} \u304cYYYY-MM-DD\u5f62\u5f0f\u3067\u7f6e\u63db\u3055\u308c\u307e\u3059'),
        ),
        migrations.AlterField(
            model_name='query',
            name='preview_sql',
            field=models.TextField(blank=True, help_text='LIMIT 100\u7a0b\u5ea6\u63a8\u5968\u304b\u3082\u3002{START_DATE} {END_DATE} \u304cYYYY-MM-DD\u5f62\u5f0f\u3067\u7f6e\u63db\u3055\u308c\u307e\u3059'),
        ),
        migrations.AlterField(
            model_name='query',
            name='use_legacy_sql',
            field=models.BooleanField(default=True, help_text='\u30b9\u30bf\u30f3\u30c0\u30fc\u30c9SQL\u3092\u4f7f\u3044\u305f\u3044\u5834\u5408\u306f\u30c1\u30a7\u30c3\u30af\u3092\u5916\u3057\u3066\u304f\u3060\u3055\u3044\u3002'),
        ),
        migrations.AlterField(
            model_name='query',
            name='users',
            field=models.ManyToManyField(help_text='\u8868\u793a\u3068CSV\u30c0\u30a6\u30f3\u30ed\u30fc\u30c9\u3067\u304d\u308b\u30e6\u30fc\u30b6\u30fc\u3092\u6307\u5b9a\u3057\u3066\u304f\u3060\u3055\u3044', to=settings.AUTH_USER_MODEL),
        ),
    ]
