# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-11 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_auto_20170831_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='use_custom_replacement',
            field=models.BooleanField(default=False, help_text='START_DATE, END_DATE\u4ee5\u5916\u306e\u7f6e\u63db\u3092\u4f7f\u3044\u305f\u3044\u5834\u5408\u306f\u30c1\u30a7\u30c3\u30af\u3057\u3066\u304f\u3060\u3055\u3044'),
        ),
    ]
