FROM python:3.5-alpine
MAINTAINER yu_yamazaki@bizocean.co.jp

RUN pip3 install --upgrade -q \
google-api-python-client \
redis \
pyslack \
requests \
gspread \
oauth2client

ENV REDISMASTER_SERVICE_HOST localhost
ENV REDISMASTER_SERVICE_PORT 6379
ENV LOG_LEVEL WARNING

ENV JSON_KEY_FILE keys/your_google_key_file.json
ENV SPREAD_SHEET_KEY sample

RUN mkdir /oceanus/
COPY app /oceanus/app
WORKDIR /oceanus/app/

CMD ["python3.5","revelation.py"]
