apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: 2016-08-18T07:10:13Z
  generation: 4
  labels:
    run: redis323
  name: redis323
  namespace: default
  resourceVersion: "1224335"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/redis323
  uid: cee53753-6512-11e6-a957-42010af00012
spec:
  replicas: 1
  selector:
    matchLabels:
      run: redis323
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: redis323
    spec:
      containers:
      - image: asia.gcr.io/oceanus-dev/oceanus-redis:v3.2.3
        imagePullPolicy: IfNotPresent
        name: redis323
        ports:
        - containerPort: 6379
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /data
          name: redis-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - gcePersistentDisk:
          fsType: ext4
          pdName: redis-data
        name: redis-data
status:
  availableReplicas: 1
  observedGeneration: 4
  replicas: 1
  updatedReplicas: 1
